=== MarioGabrielNuez/Lenguaje_De_Marcas/ABR04_DTD/Ejemplo 2 - Validacion con DTD externo/validacion.dtd
<!ELEMENT BDusuarios (usuario)+>
<!ELEMENT usuario (nombre, email, fechaNac)>
<!ATTLIST usuario
    clave CDATA #REQUIRED
    dni CDATA #REQUIRED
>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT fechaNac EMPTY>
<!ENTITY fecha "22-04-2022">

=== MarioGabrielNuez/Lenguaje_De_Marcas/ABR04_DTD/Ejemplo 2 - Validacion con DTD externo/datos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE BDusuarios SYSTEM "validacion.dtd">
<BDusuarios>
    <usuario clave="****" dni="********">
        <nombre>Sergio</nombre>
        <email>usersergio@user.com &fecha;</email>
        <fechaNac></fechaNac>
    </usuario>
    <usuario clave="****" dni="********">
        <nombre>Antonio</nombre>
        <email>userantonio@user.com</email>
        <fechaNac></fechaNac>
    </usuario>
</BDusuarios>
